twp_comment:
    resource: "@TwpCommentBundle/Controller/"
    type:     annotation
    prefix:   /

twp_idea:
    resource: "@TwpIdeaBundle/Controller/"
    type:     annotation
    prefix:   /

twp_dashboard:
    resource: "@TwpDashboardBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
